# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAgent',
            fields=[
                ('agent_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(max_length=25)),
                ('phone_no', models.CharField(db_column='phone no', max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('password', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'delivery_agent',
                'managed': False,
            },
        ),
    ]
