# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('rating_id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField()),
                ('date', models.DateField()),
                ('rating', models.CharField(max_length=25)),
                ('review', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'rating',
                'managed': False,
            },
        ),
    ]
