# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Train',
            fields=[
                ('train_id', models.AutoField(primary_key=True, serialize=False)),
                ('train_name', models.CharField(max_length=20)),
                ('route', models.CharField(max_length=60)),
                ('time', models.TimeField()),
            ],
            options={
                'db_table': 'train',
                'managed': False,
            },
        ),
    ]
