# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('medicine_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('description', models.CharField(max_length=25)),
                ('price', models.CharField(max_length=10)),
                ('image', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'medicine',
                'managed': False,
            },
        ),
    ]
