# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('doctor_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=25)),
                ('age', models.CharField(max_length=25)),
                ('gender', models.CharField(max_length=25)),
                ('address', models.CharField(max_length=25)),
                ('specialization', models.CharField(max_length=25)),
                ('experience', models.CharField(max_length=25)),
                ('email', models.CharField(max_length=25)),
                ('phone_no', models.IntegerField(db_column='phone no')),
                ('password', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'doctor',
                'managed': False,
            },
        ),
    ]
