# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=11)),
                ('quantity', models.IntegerField()),
                ('seat_no', models.CharField(max_length=20)),
                ('amount', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'order',
                'managed': False,
            },
        ),
    ]
