# Generated by Django 3.2.21 on 2024-01-15 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AssignDeliveryAgent',
            fields=[
                ('assign_id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'assign_delivery_agent',
                'managed': False,
            },
        ),
    ]
